arch:
- aarch64
- amd64
- armv7
- i386
codenotary: alexvbokov@gmail.com
description: precipitation - calc rain and snow amount (—Å) Alex Bokov
hassio_api: true
homeassistant_api: true
init: false
host_network: true
map:
- config:rw
name: precipitation
options:
  api_key: "8f093e433c0c2b70df025f186097d63d"
schema:
  api_key: str
slug: precipitation
startup: services
url: https://github.com/alexvbokov/hassio-addons
version: 1.34
