arch:
- aarch64
- amd64
- armv7
- i386
codenotary: alexvbokov@gmail.com
description: cloud.io --hassio_role: default-- help access hass.io from outside (—Å) Alex Bokov
hassio_api: true
hassio_role: default
init: false
host_network: true
map:
- config:rw
name: cloud_io
options:
  client_id: 23456
  hassio_ip: 192.168.0.100
schema:
  client_id: int
  hassio_ip: str?
slug: cloud_io
startup: services
url: https://github.com/alexvbokov/hassio-addons
version: 1.03
